# Generated by Django 5.0.6 on 2024-07-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=20, verbose_name='Your first name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=30, verbose_name='Your last name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=' Enter the category of your Recipe', max_length=50, verbose_name='Recipe Category')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title', max_length=50, verbose_name='Recipe title')),
                ('cooking_time', models.DecimalField(decimal_places=1, help_text='Enter estimated cooking time', max_digits=3, verbose_name='Cooking time (in mins)')),
                ('description', models.TextField(help_text='Provide the quick description', max_length=150, verbose_name='Recipe description')),
                ('cooking_method', models.TextField(help_text='Describe the cooking process', max_length=1000, verbose_name='Recipe description')),
                ('author', models.ManyToManyField(help_text='Enter the author(s) of the recipe', to='myapp.author', verbose_name='Recipe author(s)')),
                ('category', models.ForeignKey(help_text='Enter the recipe category', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category', verbose_name='Recipe category')),
            ],
        ),
    ]
