# Generated by Django 5.0.6 on 2024-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(help_text='Upload a photo', null=True, upload_to='images', verbose_name='Photo'),
        ),
    ]
